GET http://localhost:8081/


POST http://localhost:8081/register
Content-Type: application/json

{
    "email": "6Abc123!@a.de",
    "password": "6Abc123!@a.de"
}

POST http://localhost:8081/login
Content-Type: application/json

{
    "email": "6Abc123!@a.de",
    "password": "6Abc123!@a.de"
}